# Generated by Django 5.0.14 on 2025-06-04 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_rec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSchedule',
            fields=[
                ('organization_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('created_id', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_id', models.IntegerField()),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'organization_schedules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_code', models.CharField(max_length=10)),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('flexible_min', models.IntegerField(blank=True, default=0, null=True)),
                ('grace_in_min', models.IntegerField(blank=True, default=0, null=True)),
                ('grace_out_min', models.IntegerField(blank=True, default=0, null=True)),
                ('open_shift', models.IntegerField(blank=True, default=0, null=True)),
                ('night_shift', models.IntegerField(blank=True, default=0, null=True)),
                ('sch_color', models.CharField(blank=True, max_length=10, null=True)),
                ('ramadan_flag', models.BooleanField(default=False)),
                ('required_work_hours', models.DateTimeField(blank=True, null=True)),
                ('Status_Flag', models.BooleanField(default=True)),
                ('created_id', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_id', models.IntegerField()),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'schedules',
                'managed': False,
            },
        ),
    ]
