# Generated by Django 5.0.14 on 2025-06-04 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_rec', '0002_organizationschedule_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('employee_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('created_id', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_id', models.IntegerField()),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'employee_schedules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupSchedule',
            fields=[
                ('group_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('created_id', models.IntegerField()),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_id', models.IntegerField()),
                ('last_updated_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'group_schedules',
                'managed': False,
            },
        ),
    ]
