# Generated by Django 5.0.14 on 2025-06-04 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_rec', '0003_employeeschedule_groupschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEventTransaction',
            fields=[
                ('transction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_time', models.DateTimeField()),
                ('reason', models.CharField(max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('reader_id', models.IntegerField(blank=True, null=True)),
                ('user_entry_flag', models.IntegerField()),
                ('created_id', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_id', models.IntegerField()),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'employee_event_transactions',
                'managed': False,
            },
        ),
    ]
