# Generated by Django 5.0.14 on 2025-07-10 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_rec', '0005_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecModule',
            fields=[
                ('module_id', models.AutoField(db_column='module_id', primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=50)),
                ('last_updated_id', models.IntegerField()),
                ('last_updated_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sec_modules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecPrivilegeGroup',
            fields=[
                ('privilege_group_id', models.AutoField(db_column='privilege_group_id', primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50)),
                ('last_updated_id', models.IntegerField()),
                ('last_updated_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sec_privilege_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecRole',
            fields=[
                ('role_id', models.AutoField(db_column='role_id', primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20)),
                ('editable_flag', models.BooleanField(default=False)),
                ('last_updated_id', models.IntegerField()),
                ('last_updated_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sec_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecRolePrivilege',
            fields=[
                ('role_privilege_id', models.AutoField(db_column='role_privilege_id', primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('ALL', 'All'), ('NODE', 'Node'), ('OWN', 'Own')], max_length=5)),
                ('access_flag', models.BooleanField(default=False)),
                ('view_flag', models.BooleanField(default=False)),
                ('create_flag', models.BooleanField(default=False)),
                ('edit_flag', models.BooleanField(default=False)),
                ('delete_flag', models.BooleanField(default=False)),
                ('last_updated_id', models.IntegerField()),
                ('last_updated_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sec_role_privileges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecSubModule',
            fields=[
                ('sub_module_id', models.AutoField(db_column='sub_module_id', primary_key=True, serialize=False)),
                ('sub_module_name', models.CharField(max_length=50)),
                ('last_updated_id', models.IntegerField()),
                ('last_updated_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sec_sub_modules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecUserRole',
            fields=[
                ('user_role_id', models.AutoField(db_column='user_role_id', primary_key=True, serialize=False)),
                ('last_updated_id', models.IntegerField()),
                ('last_updated_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sec_user_roles',
                'managed': False,
            },
        ),
    ]
