# Generated by Django 5.0.14 on 2025-07-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_rec', '0006_secmodule_secprivilegegroup_secrole_secroleprivilege_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEmployeeAttendanceDetails',
            fields=[
                ('daily_EmployeeAttendanceDetails_id', models.AutoField(primary_key=True, serialize=False)),
                ('Ddate', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
                ('late', models.IntegerField(blank=True, null=True)),
                ('early', models.IntegerField(blank=True, null=True)),
                ('workmts_row_timediff', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_EmployeeAttendanceDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('emp_no', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=200)),
                ('organization_eng', models.CharField(max_length=255)),
                ('managername_eng', models.CharField(max_length=200, null=True)),
                ('transdate', models.DateField()),
                ('sch_in', models.CharField(max_length=5)),
                ('sch_out', models.CharField(max_length=5)),
                ('punch_in', models.TimeField(null=True)),
                ('punch_out', models.TimeField(null=True)),
                ('late', models.IntegerField(null=True)),
                ('early', models.IntegerField(null=True)),
                ('workmts_row_timediff', models.IntegerField(null=True)),
                ('absentmts', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'vw_DailyMove',
                'managed': False,
            },
        ),
    ]
